asset_dir = "assets"
exclude_assets = []
write_dir = "src/Assets"

[creator]
type = "user"
id = 2070986515

[codegen]
output_name = "_asphalt.luau"
typescript = false
style = "flat"
strip_extension = true
